### ISSUE TITLE
Make sure a meeting is ended before creating it

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton_rails#121]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1867, http://dev.mconf.org/redmine/issues/1867

---

Before sending a "create" request to create a meeting, the gem should make sure the meeting is not already created by sending an "end" request.
This would prevent failures in "create" calls when users change the attributes of a room that is already created and try to join it. The full scenario usually is:

* The user starts a meeting.
* The user leaves the meeting without making a call to "end" (by closing the browser, for example).
* The user changes some attribute of the room.
* The user tries to join the meeting again.  This should be done within a few minutes or seconds after the previous time he joined the meeting.

One possible drawback of calling "end" before creating the meeting is that it might cause issues with concurrent calls to create a meeting. if the user clicks to join the meeting twice, opening to windows that will both join the meeting at the same time, what happens?

**Comment by lfzawacki** [comment]
Having a real hard time trying to reproduce. The rooms indeed stay 2-5 minutes open after you close the browser window, but a subsequent join to the meeting with different parameters seems to close the meeting, apply the new settings and work as expected.

**Comment by daronco** [comment]
We have already the code that forces an "end meeting" before the meeting is created, to make sure there will be no conflict in the parameters when creating a room that is already in memory in the webconf server, see https://github.com/mconf/bigbluebutton_rails/blob/master/app/models/bigbluebutton_room.rb#L259
It was made as part of #83.

Since we have a solution implemented and can't reproduce the issue, I'll assume this is solved. If it happens again we'll need more details on how to reproduce it (which will probably be a very specific situation).
