### ISSUE TITLE
Rails 3 BigbluebuttonRails::ServerRequired in Bigbluebutton

### ISSUE THREAD

**Issue by iamsujitpranav** [mconf/bigbluebutton_rails#30]
Hi,

Iam getting the following error  when I used below gem

" gem "bigbluebutton_rails","~> 1.3.0" "

BigbluebuttonRails::ServerRequired in Bigbluebutton
translation missing: en.bigbluebutton_rails.rooms.errors.server.not_set

bigbluebutton_rails (1.3.0) app/models/bigbluebutton_room.rb:263:in `require_server'
bigbluebutton_rails (1.3.0) app/models/bigbluebutton_room.rb:115:in `fetch_is_running?'
bigbluebutton_rails (1.3.0) app/controllers/bigbluebutton/rooms_controller.rb:327:in `join_internal'
bigbluebutton_rails (1.3.0) app/controllers/bigbluebutton/rooms_controller.rb:121:in `join'
actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.13) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.13) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.13) lib/active_support/callbacks.rb:502:in `_run__114511248122689171__process_action__4511386445062351138__callbacks'

**Comment by daronco** [comment]
Your `BigbluebuttonRoom` instance has no server associated to it, so the gem doesn't know where to send API requests to. Just pass the `BigbluebuttonServer` when you create the room and it should be ok.
This is an example of how it is done in Mconf-Web: https://github.com/mconf/mconf-web/blob/master/app/models/user.rb#L137

Also, consider using version 1.4.0 or even the version from master (that's the one we use on Mconf-Web), since 1.3.0 is quite old already.

**Comment by daronco** [comment]
Hi @iamsujitpranav, are you still having this issue?

**Comment by iamsujitpranav** [comment]
hi @daronco  . Its running perfectly now. I am sorry I couldn't reply early. Thanks a lot to you and your team. I am more interested in contributing to this gem. If there is any way  I can help you please let me know. Thanks again..! :)
